name: ci-riscv64
run-name:
on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

defaults:
  run:
    shell: bash

jobs:
  riscv-cross-compile:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create environment
        run: |
          sudo apt update
          sudo apt install -y crossbuild-essential-riscv64 cmake git
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: cat /etc/apt/sources.list
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: build riscv64-cross
        run: |
          cd  ${{ github.workspace }} &&  mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain-riscv64.cmake ../ && make -j
      - name: build dynamorio riscv       
        run: |
          sudo apt-get update
          sudo apt-get -y install doxygen vera++ cmake crossbuild-essential-riscv64 git  \
            qemu-user qemu-user-binfmt
          sudo sh -c "echo 'deb [trusted=yes arch=riscv64] http://deb.debian.org/debian-ports sid main' |tee -a /etc/apt/sources.list"
          apt download libunwind8:riscv64 libunwind-dev:riscv64 liblzma5:riscv64 \
            zlib1g:riscv64 zlib1g-dev:riscv64 libsnappy1v5:riscv64 libsnappy-dev:riscv64 \
            liblz4-1:riscv64 liblz4-dev:riscv64
          mkdir ../extract
          for i in *.deb; do dpkg-deb -x $i ../extract; done
          for i in include lib; do sudo rsync -av ../extract/usr/${i}/riscv64-linux-gnu/ /usr/riscv64-linux-gnu/${i}/; done
          sudo rsync -av ../extract/usr/include/ /usr/riscv64-linux-gnu/include/
          sudo rsync -av ../extract/lib/riscv64-linux-gnu/ /usr/riscv64-linux-gnu/lib/ 
      
      - name: test suite
        working-directory: ${{ github.workspace }}        
        run: |
          git clone https://github.com/shiptux/dynamorio.git
          cd dynamorio 
          ./suite/runsuite_wrapper.pl automated_ci 64_only
        env:
          DYNAMORIO_CROSS_RISCVXX_LINUX_ONLY: yes
          CI_TRIGGER: ${{ github.event_name }}
          CI_BRANCH: ${{ github.ref }}
          run: echo "🍏 This job's status is ${{ job.status }}."

  riscv-debian-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create environment
        run: |
          sudo apt update
          sudo apt install -y crossbuild-essential-riscv64 cmake 
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: build riscv64-cross
        run: |
          cd  ${{ github.workspace }} &&  mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain-riscv64.cmake ../ && make -j
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: build dynamorio riscv       
        run: |
          sudo apt-get update
          sudo apt-get -y install doxygen vera++ cmake crossbuild-essential-riscv64 git  \
          qemu-user qemu-user-binfmt
          sudo sh -c "echo 'deb [trusted=yes arch=riscv64] http://deb.debian.org/debian-ports sid main' |tee -a /etc/apt/sources.list"
          sudo apt update
          apt download libunwind8:riscv64 libunwind-dev:riscv64 liblzma5:riscv64 \
            zlib1g:riscv64 zlib1g-dev:riscv64 libsnappy1v5:riscv64 libsnappy-dev:riscv64 \
            liblz4-1:riscv64 liblz4-dev:riscv64
          mkdir ../extract
          for i in *.deb; do dpkg-deb -x $i ../extract; done
          for i in include lib; do sudo rsync -av ../extract/usr/${i}/riscv64-linux-gnu/ /usr/riscv64-linux-gnu/${i}/; done
          sudo rsync -av ../extract/usr/include/ /usr/riscv64-linux-gnu/include/
          sudo rsync -av ../extract/lib/riscv64-linux-gnu/ /usr/riscv64-linux-gnu/lib/ 
      
      - name: test suite
        working-directory: ${{ github.workspace }}        
        run: |
          git clone https://github.com/shiptux/dynamorio.git
          cd dynamorio 
          ./suite/runsuite_wrapper.pl automated_ci 64_only
        env:
          DYNAMORIO_CROSS_RISCVXX_LINUX_ONLY: yes
          CI_TRIGGER: ${{ github.event_name }}
          CI_BRANCH: ${{ github.ref }}
          run: echo "🍏 This job's status is ${{ job.status }}."
